database:
  type: sqlite # mysql, sqlite
  host: localhost
  port: 3306
  name:
  username:
  password:

economy:
  transaction_fee: 0.1
  daily_reward_hours_cooldown: 24
  daily_reward_min: 100
  daily_reward_max: 1000
  initial_balance: 1000
  initial_bank_balance: 0
  max_balance: 5000
